# Generated by Django 5.2.3 on 2025-06-11 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('rest_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant restant')),
                ('state', models.CharField(choices=[('draft', 'Brouillon'), ('signed', 'Signé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='draft', max_length=20, verbose_name='État')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='shop.client', verbose_name='Client')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='users.user', verbose_name='Commercial')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'db_table': 'contract',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('event_start', models.DateTimeField(verbose_name="Début de l'événement")),
                ('event_end', models.DateTimeField(verbose_name="Fin de l'événement")),
                ('location', models.CharField(max_length=255, verbose_name='Lieu')),
                ('attendees', models.PositiveIntegerField(verbose_name='Nombre de participants')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shop.client', verbose_name='Client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shop.contract', verbose_name='Contrat')),
                ('logistic_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.user', verbose_name='Contact logistique')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'event',
                'ordering': ['event_start'],
            },
        ),
    ]
