# Generated by Django 5.2.3 on 2025-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'db_table': 'cart',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
            ],
            options={
                'verbose_name': 'Article de panier',
                'verbose_name_plural': 'Articles de panier',
                'db_table': 'cart_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('shipment_type', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('pickup', 'Retrait en magasin')], default='standard', max_length=20, verbose_name="Type d'expédition")),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse de livraison')),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse de facturation')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de suivi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'order',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('promotion_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix promotionnel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('maxi_order_quantity', models.PositiveIntegerField(default=9999, verbose_name='Quantité maximale par commande')),
                ('editor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Éditeur')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
    ]
