# Generated by Django 5.2.3 on 2025-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder',
            field=models.BooleanField(default=False, verbose_name='Précommande'),
        ),
    ]
