# Generated by Django 5.2.3 on 2025-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_preorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='Non défini', max_length=50, null=True, verbose_name='Numéro de suivi'),
        ),
    ]
