# Generated by Django 5.2.3 on 2025-06-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Worker', 'Worker'), ('Admin', 'Admin'), ('Client', 'Client')], default='Client', max_length=20, verbose_name='Rôle'),
        ),
    ]
